### PR TITLE
App to get metadata for larger image set and make labels

### PR DESCRIPTION
**Pull request by rasutt**
I have added a folder containing a java app I wrote to get the data for the larger data set and make the labels, as well as the data and labels I got with it. It includes a readme, the Jaunt webscraping package, the source code for the app, and three data files.  

This is my first pull request, sorry if I screw it up.

### CODE REVIEW

**Comment by a-i-joe** [comment]
Hi @rasutt . Thanks for making the first PR, and a really valuable contribution. I think we should definitely accept this contribution, but there are a couple of practical points if you could kindly adjust first.

- Don't commit the data files themselves to the repository. Sorry I didn't mention this earlier. I've now added this point to the readme. It's just the simplest way to make sure we are meeting all the T&C's for the datasets. So, rather than committing the datasets, if you could please explain in your readme how to re-create them using your java program, that would be much appreciated.
- Best practice is to not commit any binary files to github, so if you could please remove the .jar and .class files, but keep the .java file and mention which version of java/maven is needed to compile or run it.
- Please also remove the .jar and .txt files for the jaunt dependency, and rather define the dependency with a Maven configuration file see https://spring.io/guides/gs/maven/ and https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management and https://mvnrepository.com/artifact/org.jaunt-lang/jaunt

It might pay to add a `.gitignore` file in your folder, which stops the datasets and binaries which your program produces from being accidentally committed.

Yell out here, or on our message boards, if you need help with any of this.

Thanks again!

**Comment by rasutt** [comment]
Hi @a-i-joe .  Thanks for your patience and good advice.  

I've deleted the binaries and data files as you suggested.  

I tried to create a Maven config file but eventually realized that the Jaunt package I'm using is different from the one you linked to, and is not actually available through Maven.  From what I can tell this means that there isn't much benefit in creating a Maven file for it, and if I'm wrong about that I might need some help with it cause I'm finding the process quite complicated.  Otherwise I've enlarged the readme to include instructions on how to download and use the package, which is pretty easy.

I hope these changes will bring the branch closer to being ready to merge but please let me know if there are any more issues.

Cheers!

**Comment by a-i-joe** [comment]
Looks good @rasutt . Just one more small tweak: The .gitignore you have copied is based off a python-oriented gitignore, and the exclusions you've added are too specific. I recommend replacing the contents of your gitignore with this:

```glob
#datasets
*.json

# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
hs_err_pid*
```

Taken from here, with one additional line to exclude .json files: https://github.com/github/gitignore/blob/master/Java.gitignore

Thanks again

**Comment by rasutt** [comment]
Ah that was dumb, thanks alot @a-i-joe .   I changed it and also included *.csv for the other dataset it makes.

**Comment by a-i-joe** [comment]
+1

**Comment by GregTarr** [comment]
Hey Robin - I am having difficulty getting the webscraper to work - could you please send me the file with the labels for the largest dataset?


Cheers,

Greg

________________________________

**Pull request merged**
